// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmefovbhjechwtbhigdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptZWZvdmJoamVjaHd0YmhpZ2RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1Njk0MzYsImV4cCI6MjA2MzE0NTQzNn0.QwVIKnVZC16TVaI3IaBhjHdUafl-iG2Rji8784ln8LU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);